apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
  namespace: nexus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.120
    path: /opt/kubernetes-nfs/nexus
  persistentVolumeReclaimPolicy: Retain
---
# pvc-nfs.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-pvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nexus-data-pv