apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: POSTGRESQL_USERNAME
              value: bn_sonarqube
            - name: POSTGRESQL_PASSWORD
              value: bitnami
            - name: POSTGRESQL_DATABASE
              value: bitnami_sonarqube
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: sonarqube-pg-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: sonarqube
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgresql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:25.6.0.109173-community
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "6Gi"
              cpu: "2"
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://postgresql:5432/bitnami_sonarqube
            - name: SONAR_JDBC_USERNAME
              value: bn_sonarqube
            - name: SONAR_JDBC_PASSWORD
              value: bitnami
            - name: SONARQUBE_DATABASE_USER
              value: bn_sonarqube
            - name: SONARQUBE_DATABASE_PASSWORD
              value: bitnami
            - name: SONARQUBE_DATABASE_NAME
              value: bitnami_sonarqube
            - name: SONARQUBE_PASSWORD
              value: AdmiN@123Sonar
            - name: SONARQUBE_WEB_JAVA_OPTS
              value: "-Xms2G -Xmx4G"
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions

      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extn-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
  selector:
    app: sonarqube
